export const SEARCH_KEYWORDS = [
  'luggage',
  'suitcase',
  'travel bag',
  'packing cubes',
  'packing organizer',
  'toiletry bag',
  'garment bag',
  'travel adapter',
  'universal adapter',
  'portable charger',
  'cable organizer',
  'power bank',
  'travel pillow',
  'neck pillow',
  'eye mask sleep',
  'compression socks',
  'earplugs sleep',
  'RFID wallet',
  'passport holder',
  'luggage tag',
  'luggage lock',
  'bluetooth earbuds travel',
  'noise cancelling',
] as const
