/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    collections: Collection;
    orders: Order;
    customers: Customer;
    editorial: Editorial;
    'digital-assets': DigitalAsset;
    'candidate-products': CandidateProduct;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    editorial: EditorialSelect<false> | EditorialSelect<true>;
    'digital-assets': DigitalAssetsSelect<false> | DigitalAssetsSelect<true>;
    'candidate-products': CandidateProductsSelect<false> | CandidateProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt_text: string;
  caption?: string | null;
  source?: ('upload' | 'cj_import' | 'supplier') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Used for URL paths.
   */
  slug: string;
  /**
   * Category description for SEO and display.
   */
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Leave empty for top-level categories. Set to a parent for sub-categories.
   */
  parent?: (number | null) | Category;
  /**
   * 0 = top-level, 1 = sub-category. Auto-set based on parent.
   */
  depth: number;
  /**
   * Sort priority within the same depth level. Lower = first.
   */
  display_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Used for URL paths.
   */
  slug: string;
  /**
   * Controls fulfillment routing and which fields are visible.
   */
  product_type:
    | 'physical'
    | 'digital_download'
    | 'esim'
    | 'insurance'
    | 'fare_report'
    | 'claim_package'
    | 'service_booking'
    | 'subscription'
    | 'bundle';
  status: 'draft' | 'active' | 'archived';
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * One-liner for cards and search results. Max 200 characters.
   */
  short_description?: string | null;
  /**
   * Price in cents. $9.99 = 999
   */
  price: number;
  /**
   * Strike-through "was" price in cents.
   */
  compare_at_price?: number | null;
  /**
   * Supplier cost in cents. For margin tracking.
   */
  cost?: number | null;
  currency: 'usd' | 'eur' | 'gbp' | 'cad' | 'aud' | 'jpy';
  /**
   * First image is the primary/hero image.
   */
  images?: (number | Media)[] | null;
  /**
   * Optional. Falls back to first image.
   */
  thumbnail?: (number | null) | Media;
  supplier: 'cj' | 'airalo' | 'cover_genius' | 'printful' | 'manual' | 'api_generated';
  /**
   * External ID in the supplier system.
   */
  supplier_product_id?: string | null;
  /**
   * Link to product in supplier dashboard.
   */
  supplier_url?: string | null;
  categories?: (number | Category)[] | null;
  /**
   * Which merchandised collections this product appears in.
   */
  collections_ref?: (number | Collection)[] | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Enable named option types (Color, Size, etc.) and variant combinations.
   */
  has_variants?: boolean | null;
  /**
   * Define option dimensions (e.g., Color, Size). Max 3.
   */
  options?:
    | {
        option_name: string;
        values: {
          value: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Each variant maps to a specific combination of option values.
   */
  variants?:
    | {
        option_selections?:
          | {
              option_name: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Auto-generated display label (e.g., "Black / Large"). Editable.
         */
        variant_label?: string | null;
        sku?: string | null;
        /**
         * In cents. Overrides product-level price.
         */
        price?: number | null;
        /**
         * In cents.
         */
        compare_at_price?: number | null;
        supplier_variant_id?: string | null;
        weight_grams?: number | null;
        inventory_count?: number | null;
        /**
         * Variant-specific image (e.g., color swatch).
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  inventory_tracked?: boolean | null;
  /**
   * Current stock. Synced from CJ for dropship items.
   */
  inventory_count?: number | null;
  weight_grams?: number | null;
  /**
   * Internal SKU for non-variant products.
   */
  sku?: string | null;
  /**
   * Link to downloadable file/asset.
   */
  digital_asset?: (number | null) | DigitalAsset;
  /**
   * Inngest function identifier (e.g., fulfill-esim, fulfill-fare-report).
   */
  fulfillment_handler?: string | null;
  /**
   * Handler-specific configuration (Airalo package params, fare report defaults, etc.).
   */
  api_config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Component products in this bundle. Each fulfilled independently.
   */
  bundle_items?:
    | {
        product: number | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Falls back to product title.
     */
    meta_title?: string | null;
    /**
     * Falls back to short description.
     */
    meta_description?: string | null;
    /**
     * Falls back to first product image.
     */
    og_image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Used for URL paths.
   */
  slug: string;
  /**
   * Collection page intro copy.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured_image?: (number | null) | Media;
  /**
   * Ordered list of products in this collection.
   */
  products?: (number | Product)[] | null;
  trip_type?:
    | (
        | 'carry_on'
        | 'checked_bag'
        | 'red_eye'
        | 'international'
        | 'budget'
        | 'business'
        | 'family'
        | 'adventure'
        | 'digital_nomad'
      )
    | null;
  /**
   * Sort priority on homepage/nav. Lower = first.
   */
  display_order?: number | null;
  /**
   * If true, this collection can be featured in the homepage hero.
   */
  hero_enabled?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digital-assets".
 */
export interface DigitalAsset {
  id: number;
  /**
   * Internal label (e.g., "SFO Airport Briefing v2").
   */
  title: string;
  /**
   * Which product this asset belongs to.
   */
  product?: (number | null) | Product;
  delivery_type: 'email_attachment' | 'signed_download_url' | 'api_provisioned';
  /**
   * Inngest function identifier. Overrides the product-level handler if set.
   */
  fulfillment_handler?: string | null;
  /**
   * Version tracking (e.g., "1.2", "March 2026").
   */
  version?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Auto-generated sequential (e.g., TL-10001).
   */
  order_number: string;
  /**
   * Null for guest checkout.
   */
  customer?: (number | null) | Customer;
  /**
   * Denormalized for guest orders and quick lookup.
   */
  customer_email: string;
  status: 'pending' | 'paid' | 'processing' | 'partially_fulfilled' | 'fulfilled' | 'cancelled' | 'refunded';
  line_items?:
    | {
        product?: (number | null) | Product;
        /**
         * Snapshot at time of purchase.
         */
        title: string;
        /**
         * Snapshot of variant (e.g., "Black / Large"). Null if no variant.
         */
        variant_label?: string | null;
        quantity: number;
        /**
         * In cents. Immutable snapshot.
         */
        price_at_purchase: number;
        /**
         * ISO 4217 code snapshot.
         */
        currency_at_purchase?: string | null;
        /**
         * Drives fulfillment routing.
         */
        product_type: string;
        fulfillment_status?:
          | ('pending' | 'processing' | 'shipped' | 'delivered' | 'fulfilled_digital' | 'failed')
          | null;
        /**
         * CJ order ID, Airalo order ID, etc.
         */
        supplier_order_id?: string | null;
        tracking_number?: string | null;
        tracking_url?: string | null;
        id?: string | null;
      }[]
    | null;
  payment: {
    stripe_payment_intent_id?: string | null;
    stripe_checkout_session_id?: string | null;
    /**
     * In cents.
     */
    subtotal: number;
    /**
     * In cents. 0 for digital-only.
     */
    shipping_cost?: number | null;
    /**
     * In cents.
     */
    tax?: number | null;
    /**
     * In cents.
     */
    total: number;
    /**
     * ISO 4217 code.
     */
    currency: string;
  };
  /**
   * Only relevant for orders containing physical items.
   */
  shipping?: {
    name?: string | null;
    address_line1?: string | null;
    address_line2?: string | null;
    city?: string | null;
    state?: string | null;
    postal_code?: string | null;
    /**
     * ISO 3166-1 alpha-2.
     */
    country?: string | null;
  };
  /**
   * Admin-only internal notes.
   */
  notes?: string | null;
  /**
   * Logged errors from Inngest handlers.
   */
  fulfillment_errors?:
    | {
        error: string;
        occurred_at?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name?: string | null;
  traveler_profile?: {
    home_airport?: string | null;
    passport_country?: string | null;
    bag_preferences?: ('carry_on_only' | 'one_checked' | 'two_checked' | 'no_preference') | null;
    seat_preferences?: ('window' | 'aisle' | 'middle' | 'no_preference') | null;
    /**
     * Always needs WiFi (used for fare reports).
     */
    wifi_priority?: boolean | null;
  };
  /**
   * Populated from orders. Can also query via Orders.customer.
   */
  orders?: (number | Order)[] | null;
  /**
   * For Phase 2 subscription products.
   */
  subscription_status?: ('none' | 'active' | 'cancelled' | 'past_due') | null;
  /**
   * Stripe customer ID for payment method reuse.
   */
  stripe_customer_id?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial".
 */
export interface Editorial {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Used for URL paths.
   */
  slug: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short preview for cards and feeds. Max 300 characters.
   */
  excerpt?: string | null;
  featured_image?: (number | null) | Media;
  category?: ('guide' | 'review' | 'comparison' | 'how_to' | 'deal_alert' | 'news') | null;
  /**
   * Products referenced or recommended in this article.
   */
  related_products?: (number | Product)[] | null;
  related_collections?: (number | Collection)[] | null;
  author?: string | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Explicit publish date for display and sorting.
   */
  published_at?: string | null;
  seo?: {
    /**
     * Falls back to article title.
     */
    meta_title?: string | null;
    /**
     * Falls back to excerpt.
     */
    meta_description?: string | null;
    /**
     * Falls back to featured image.
     */
    og_image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-products".
 */
export interface CandidateProduct {
  id: number;
  supplier: 'cj' | 'airalo' | 'cover_genius' | 'printful' | 'manual' | 'api_generated';
  /**
   * External product ID used to deduplicate supplier imports.
   */
  supplier_product_id: string;
  supplier_name: string;
  /**
   * Wholesale price from supplier, in cents.
   */
  supplier_price: number;
  supplier_category?: string | null;
  /**
   * Primary supplier image URL for admin preview; not downloaded yet.
   */
  supplier_image_url?: string | null;
  /**
   * Full raw supplier API response used by the import pipeline.
   */
  supplier_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  variant_count?: number | null;
  inventory?: number | null;
  search_keyword?: string | null;
  ai_score?: number | null;
  ai_rationale?: string | null;
  ai_concerns?: string | null;
  /**
   * AI-cleaned product title; falls back to supplier name before scoring.
   */
  suggested_title?: string | null;
  /**
   * Suggested retail price, in cents.
   */
  suggested_retail_price?: number | null;
  status: 'pending_review' | 'needs_review' | 'auto_rejected' | 'approved' | 'rejected' | 'imported';
  reviewed_at?: string | null;
  rejection_reason?: string | null;
  /**
   * Products collection ID created after successful import.
   */
  imported_product_id?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'editorial';
        value: number | Editorial;
      } | null)
    | ({
        relationTo: 'digital-assets';
        value: number | DigitalAsset;
      } | null)
    | ({
        relationTo: 'candidate-products';
        value: number | CandidateProduct;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt_text?: T;
  caption?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  parent?: T;
  depth?: T;
  display_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  product_type?: T;
  status?: T;
  description?: T;
  short_description?: T;
  price?: T;
  compare_at_price?: T;
  cost?: T;
  currency?: T;
  images?: T;
  thumbnail?: T;
  supplier?: T;
  supplier_product_id?: T;
  supplier_url?: T;
  categories?: T;
  collections_ref?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  has_variants?: T;
  options?:
    | T
    | {
        option_name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  variants?:
    | T
    | {
        option_selections?:
          | T
          | {
              option_name?: T;
              value?: T;
              id?: T;
            };
        variant_label?: T;
        sku?: T;
        price?: T;
        compare_at_price?: T;
        supplier_variant_id?: T;
        weight_grams?: T;
        inventory_count?: T;
        image?: T;
        id?: T;
      };
  inventory_tracked?: T;
  inventory_count?: T;
  weight_grams?: T;
  sku?: T;
  digital_asset?: T;
  fulfillment_handler?: T;
  api_config?: T;
  bundle_items?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        meta_title?: T;
        meta_description?: T;
        og_image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  featured_image?: T;
  products?: T;
  trip_type?: T;
  display_order?: T;
  hero_enabled?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  order_number?: T;
  customer?: T;
  customer_email?: T;
  status?: T;
  line_items?:
    | T
    | {
        product?: T;
        title?: T;
        variant_label?: T;
        quantity?: T;
        price_at_purchase?: T;
        currency_at_purchase?: T;
        product_type?: T;
        fulfillment_status?: T;
        supplier_order_id?: T;
        tracking_number?: T;
        tracking_url?: T;
        id?: T;
      };
  payment?:
    | T
    | {
        stripe_payment_intent_id?: T;
        stripe_checkout_session_id?: T;
        subtotal?: T;
        shipping_cost?: T;
        tax?: T;
        total?: T;
        currency?: T;
      };
  shipping?:
    | T
    | {
        name?: T;
        address_line1?: T;
        address_line2?: T;
        city?: T;
        state?: T;
        postal_code?: T;
        country?: T;
      };
  notes?: T;
  fulfillment_errors?:
    | T
    | {
        error?: T;
        occurred_at?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  traveler_profile?:
    | T
    | {
        home_airport?: T;
        passport_country?: T;
        bag_preferences?: T;
        seat_preferences?: T;
        wifi_priority?: T;
      };
  orders?: T;
  subscription_status?: T;
  stripe_customer_id?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editorial_select".
 */
export interface EditorialSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  excerpt?: T;
  featured_image?: T;
  category?: T;
  related_products?: T;
  related_collections?: T;
  author?: T;
  status?: T;
  published_at?: T;
  seo?:
    | T
    | {
        meta_title?: T;
        meta_description?: T;
        og_image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "digital-assets_select".
 */
export interface DigitalAssetsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  delivery_type?: T;
  fulfillment_handler?: T;
  version?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "candidate-products_select".
 */
export interface CandidateProductsSelect<T extends boolean = true> {
  supplier?: T;
  supplier_product_id?: T;
  supplier_name?: T;
  supplier_price?: T;
  supplier_category?: T;
  supplier_image_url?: T;
  supplier_data?: T;
  variant_count?: T;
  inventory?: T;
  search_keyword?: T;
  ai_score?: T;
  ai_rationale?: T;
  ai_concerns?: T;
  suggested_title?: T;
  suggested_retail_price?: T;
  status?: T;
  reviewed_at?: T;
  rejection_reason?: T;
  imported_product_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}